
import { Topic } from './types';

export const CHALLENGE_TOPICS: Topic[] = [
  { id: 1, title: "What is a hobby you could talk about for hours?", description: "", hints: ["Who: Who introduced you?", "What: What exactly do you do?", "Where: Where do you practice it?", "When: When did you last do it?", "Why: Why do you love it?"] },
  { id: 2, title: "What is the best piece of advice you have ever received?", description: "", hints: ["Who: Who gave you this advice?", "What: What were the exact words?", "Where: Where were you at the time?", "When: When did it help you most?", "Why: Why was it so impactful?"] },
  { id: 3, title: "If you could live anywhere in the world, where would it be?", description: "", hints: ["Who: Who would live there with you?", "What: What does the home look like?", "Where: Where is this place located?", "When: When would you move there?", "Why: Why is it better than here?"] },
  { id: 4, title: "What is the most important lesson you learned this year?", description: "", hints: ["Who: Who was involved in the lesson?", "What: What happened exactly?", "Where: Where did this take place?", "When: When did you realize the lesson?", "Why: Why will you remember it?"] },
  { id: 5, title: "If you could have dinner with any historical figure, who would it be?", description: "", hints: ["Who: Who is the famous person?", "What: What would you eat together?", "Where: Where is the restaurant?", "When: When in time would this happen?", "Why: Why do they interest you?"] },
  { id: 6, title: "What is your favorite way to spend a rainy afternoon?", description: "", hints: ["Who: Who do you spend it with?", "What: What activity do you do?", "Where: Where is your favorite spot?", "When: When does the rain start?", "Why: Why is it relaxing for you?"] },
  { id: 7, title: "If you won the lottery tomorrow, what is the first thing you would buy?", description: "", hints: ["Who: Who would you tell first?", "What: What is the specific item?", "Where: Where would you go to buy it?", "When: When would you start spending?", "Why: Why is this your priority?"] },
  { id: 8, title: "What do you think is the best way to start a productive day?", description: "", hints: ["Who: Who inspires your routine?", "What: What is the first task?", "Where: Where do you start your day?", "When: When do you wake up?", "Why: Why does this routine work?"] },
  { id: 9, title: "What is a skill you have always wanted to learn?", description: "", hints: ["Who: Who is an expert you admire?", "What: What is the specific skill?", "Where: Where would you go to learn?", "When: When will you start learning?", "Why: Why is it important to you?"] },
  { id: 10, title: "What is the most beautiful place you have ever visited?", description: "", hints: ["Who: Who were you traveling with?", "What: What did you see there?", "Where: Where is it on the map?", "When: When was your visit?", "Why: Why was it so beautiful?"] },
  { id: 11, title: "If you could change one thing about the world, what would it be?", description: "", hints: ["Who: Who would benefit most?", "What: What is the specific change?", "Where: Where is this change needed?", "When: When should it happen?", "Why: Why is it a global priority?"] },
  { id: 12, title: "What is your favorite book or movie and why?", description: "", hints: ["Who: Who is the main character?", "What: What is the central plot?", "Where: Where does the story happen?", "When: When did you first see/read it?", "Why: Why did it move you?"] },
  { id: 13, title: "What does success mean to you personally?", description: "", hints: ["Who: Who do you consider successful?", "What: What are the requirements?", "Where: Where do you see yourself?", "When: When will you be successful?", "Why: Why do you define it this way?"] },
  { id: 14, title: "If you could be an expert in any subject instantly, what would it be?", description: "", hints: ["Who: Who would you teach first?", "What: What is the subject matter?", "Where: Where would you use the skill?", "When: When would you use it most?", "Why: Why does this field matter?"] },
  { id: 15, title: "What is your proudest accomplishment so far?", description: "", hints: ["Who: Who supported your effort?", "What: What did you achieve?", "Where: Where were you at the time?", "When: When did you finish?", "Why: Why are you so proud?"] },
  { id: 16, title: "What is the most challenging thing you have ever done?", description: "", hints: ["Who: Who helped you overcome it?", "What: What was the main obstacle?", "Where: Where did this challenge occur?", "When: When was the hardest part?", "Why: Why was it so difficult?"] },
  { id: 17, title: "If you could travel back in time, which era would you visit?", description: "", hints: ["Who: Who would you want to meet?", "What: What event would you watch?", "Where: Where in the world is this?", "When: When exactly is this era?", "Why: Why does it fascinate you?"] },
  { id: 18, title: "What is the most important quality in a good friend?", description: "", hints: ["Who: Who is your best friend?", "What: What is the specific trait?", "Where: Where did you meet them?", "When: When did they show this trait?", "Why: Why is it essential?"] },
  { id: 19, title: "What is your dream job and why?", description: "", hints: ["Who: Who else works there?", "What: What are your daily duties?", "Where: Where is the office located?", "When: When do you start and finish?", "Why: Why is it your dream?"] },
  { id: 20, title: "How do you handle stress or difficult situations?", description: "", hints: ["Who: Who do you talk to for help?", "What: What is your main method?", "Where: Where do you go to relax?", "When: When do you feel stressed?", "Why: Why does your method work?"] },
  { id: 21, title: "What is your favorite childhood memory?", description: "", hints: ["Who: Who was playing with you?", "What: What were you doing?", "Where: Where was your home then?", "When: When did this happen?", "Why: Why is it special to you?"] },
  { id: 22, title: "What is a major goal you want to achieve in the next five years?", description: "", hints: ["Who: Who will help you get there?", "What: What is the specific goal?", "Where: Where will you be living?", "When: When is the deadline?", "Why: Why is this your priority?"] },
  { id: 23, title: "What do you like most about your personality?", description: "", hints: ["Who: Who noticed this trait first?", "What: What is the specific trait?", "Where: Where do you show it most?", "When: When has it been useful?", "Why: Why do you value it?"] },
  { id: 24, title: "If you could invent something to make life easier, what would it be?", description: "", hints: ["Who: Who would use it daily?", "What: What does the machine do?", "Where: Where is it installed?", "When: When was it invented?", "Why: Why is it necessary?"] },
  { id: 25, title: "What is your favorite type of music and how does it make you feel?", description: "", hints: ["Who: Who is your favorite artist?", "What: What are the main sounds?", "Where: Where do you listen to it?", "When: When do you play it?", "Why: Why do you feel this way?"] },
  { id: 26, title: "What is the best way to stay motivated when things get tough?", description: "", hints: ["Who: Who keeps you going?", "What: What is your motivation?", "Where: Where do you find focus?", "When: When do you struggle most?", "Why: Why does it work?"] },
  { id: 27, title: "If you could spend a day with a celebrity, who would it be?", description: "", hints: ["Who: Who is the star?", "What: What would you talk about?", "Where: Where would you hang out?", "When: When would you meet them?", "Why: Why did you pick them?"] },
  { id: 28, title: "What is the most interesting fact you know?", description: "", hints: ["Who: Who discovered this fact?", "What: What is the information?", "Where: Where did you learn it?", "When: When did you find out?", "Why: Why is it interesting?"] },
  { id: 29, title: "What is the most important piece of technology in your life?", description: "", hints: ["Who: Who else uses it with you?", "What: What is the device?", "Where: Where do you take it?", "When: When do you use it most?", "Why: Why can't you live without it?"] },
  { id: 30, title: "What do you want people to remember you for?", description: "", hints: ["Who: Who will tell your story?", "What: What is your main talent?", "Where: Where is your legacy?", "When: When are you most yourself?", "Why: Why does this matter?"] }
];

export const APP_STORAGE_KEY = 'speakup_challenge_progress';
